require('dotenv').config();
const Groq = require('groq-sdk');

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY2
});

// ------------------ Helper: Retry Wrapper ------------------
async function withRetries(fn, retries = 2) {
    let lastError;
    for (let i = 0; i <= retries; i++) {
        try {
            return await fn();
        } catch (err) {
            lastError = err;
            console.warn(`Attempt ${i + 1} failed:`, err.message);
        }
    }
    throw lastError;
}

// ------------------ Helper: Send request to Groq ------------------
async function getGroqResponse(prompt) {
    const chatCompletion = await groq.chat.completions.create({
        messages: [{ role: "user", content: prompt }],
        model: "llama-3.1-8b-instant",
        response_format: { type: "json_object" }
    });

    const responseContent = chatCompletion.choices?.[0]?.message?.content;

    if (!responseContent) {
        throw new Error("AI returned empty response");
    }

    try {
        return JSON.parse(responseContent);
    } catch (err) {
        console.error("Failed to parse AI JSON response:", responseContent);
        throw new Error("AI returned invalid JSON");
    }
}

// ------------------ 1. Generate Quiz ------------------
// exports.generateQuiz = async ({
//     topic,
//     subject,
//     totalQuestions,
//     difficulty,
//     adaptiveDifficultyLevel = "MEDIUM"
// }) => {
//     const prompt = `
//         You are a helpful AI assistant specialized in creating educational quizzes.
//         Generate a ${difficulty} difficulty quiz for a Computer science& engineering student on the subject of ${subject} and in the topic${topic}.
//         The quiz should have exactly ${totalQuestions} multiple-choice questions.
//         Each question object must contain:
//         - "questionText": The text of the question.
//         - "options": An array of at least 3 multiple-choice options (strings).
//         - "correctAnswer": The correct option string from the "options" array.
//         Output only the JSON array with no extra text or markdown.
//         Example:
//         [
//           {
//             "questionText": "What is the capital of France?",
//             "options": ["Paris", "London", "Rome"],
//             "correctAnswer": "Paris"
//           }
//         ]
//         The adaptive difficulty level based on past performance is ${adaptiveDifficultyLevel}.
//     `;

//     const rawResponse = await withRetries(() => getGroqResponse(prompt));

//     // Handle different response formats
//     const questionsArray = Array.isArray(rawResponse) ? rawResponse : rawResponse.questions;

//     if (!questionsArray || !Array.isArray(questionsArray)) {
//         throw new Error("AI response is not a valid array of questions.");
//     }

//     // Validate and sanitize each question
//     const validatedQuestions = questionsArray.reduce((acc, q) => {
//         const questionText = typeof q.questionText === 'string' ? q.questionText.trim() : null;
//         const options = Array.isArray(q.options)
//             ? [...new Set(q.options.filter(opt => typeof opt === 'string').map(opt => opt.trim()))]
//             : [];
//         const correctAnswer = typeof q.correctAnswer === 'string' ? q.correctAnswer.trim() : null;

//         if (questionText && correctAnswer && options.length >= 2) {
//             acc.push({ questionText, options, correctAnswer });
//         } else {
//             console.warn("Skipped invalid AI-generated question:", q);
//         }
//         return acc;
//     }, []);

//     if (validatedQuestions.length === 0) {
//         throw new Error("No valid questions generated by AI.");
//     }

//     return validatedQuestions;
// };
exports.generateQuiz = async ({
  topic,
  subject,
  totalQuestions,
  difficulty,
  adaptiveDifficultyLevel = "MEDIUM",
}) => {
  const prompt = `
    You are a helpful AI assistant specialized in creating educational quizzes.
    Generate a ${difficulty} difficulty quiz for a Computer Science & Engineering student
    on the subject of "${subject}" and the topic "${topic}".
    The quiz should have exactly ${totalQuestions} multiple-choice questions.
    Each question object must contain:
    - "questionText": The text of the question.
    - "options": An array of at least 3 multiple-choice options (strings).
    - "correctAnswer": The correct option string from the "options" array.

    Output only a valid JSON array — no markdown, no extra text, just:
    [
      {
        "questionText": "...",
        "options": ["...", "...", "..."],
        "correctAnswer": "..."
      }
    ]

    Adaptive difficulty level (based on user's performance): ${adaptiveDifficultyLevel}.
    Return ONLY the JSON array — do not include Markdown formatting or explanations.
  `;

  // Get raw AI response (usually a string)
  const rawResponse = await withRetries(() => getGroqResponse(prompt));

  let parsed;
  try {
    parsed = typeof rawResponse === "string" ? JSON.parse(rawResponse) : rawResponse;
  } catch (err) {
    console.error("Error parsing AI response:", rawResponse);
    throw new Error("AI returned non-JSON output.");
  }

  // Handle both array and object-with-questions format
  let questionsArray = [];
  if (Array.isArray(parsed)) {
    questionsArray = parsed;
  } else if (Array.isArray(parsed.questions)) {
    questionsArray = parsed.questions;
  } else {
    console.warn("Unexpected AI response structure:", parsed);
    throw new Error("AI response is not a valid array of questions.");
  }

  // Validate and sanitize each question
  const validatedQuestions = questionsArray.reduce((acc, q) => {
    const questionText =
      typeof q.questionText === "string" ? q.questionText.trim() : null;
    const options = Array.isArray(q.options)
      ? [...new Set(q.options.filter((opt) => typeof opt === "string").map((opt) => opt.trim()))]
      : [];
    const correctAnswer =
      typeof q.correctAnswer === "string" ? q.correctAnswer.trim() : null;

    if (questionText && correctAnswer && options.length >= 2) {
      acc.push({ questionText, options, correctAnswer });
    } else {
      console.warn("Skipped invalid AI-generated question:", q);
    }
    return acc;
  }, []);

  if (validatedQuestions.length === 0) {
    throw new Error("No valid questions generated by AI.");
  }

  return validatedQuestions;
};



// ------------------ 2. Generate Hint ------------------
exports.generateHint = async (questionText) => {
    const prompt = `
        You are a helpful AI assistant providing hints for a quiz.
        Provide a short, helpful hint for the following question without giving the answer:
        "${questionText}"
        Respond with a JSON object with a single key "hint".
        Example: { "hint": "This city is on the River Thames." }
    `;

    const response = await withRetries(() => getGroqResponse(prompt));

    if (!response || typeof response.hint !== 'string') {
        throw new Error("AI did not return a valid hint");
    }

    return { hint: response.hint.trim() };
};

// ------------------ 3. Generate Improvement Tips ------------------
exports.generateImprovementTips = async (incorrectQuestions) => {
    if (!Array.isArray(incorrectQuestions) || incorrectQuestions.length === 0) {
        return { tips: [] };
    }

    const questionsAndAnswers = incorrectQuestions.map(q =>
        `Question: ${q.questionText}\nCorrect Answer: ${q.correctAnswer}`
    ).join('\n\n');

    const prompt = `
        Based on the following incorrect quiz answers, provide 2 specific and actionable tips for improvement.
        Analyze the questions to identify common weaknesses.
        Respond with a JSON object with a single key "tips" which is an array of strings.
        Example: { "tips": ["Review the rules for verb conjugation.", "Practice your times tables for better speed."] }

        Incorrect questions and answers:
        ${questionsAndAnswers}
    `;

    const response = await withRetries(() => getGroqResponse(prompt));

    if (!response || !Array.isArray(response.tips)) {
        throw new Error("AI did not return a valid tips array");
    }

    return { tips: response.tips.map(t => t.trim()) };
};
